# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Door Sizing 2.ui'
#
# Created: Fri Dec 20 08:44:07 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(600, 430)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 581, 411))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setMargin(0)
        self.label_3.setIndent(10)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 4, 1, 1)
        self.addButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridLayout.addWidget(self.addButton, 6, 0, 1, 2)
        self.widthBox = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthBox.sizePolicy().hasHeightForWidth())
        self.widthBox.setSizePolicy(sizePolicy)
        self.widthBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.widthBox.setFont(font)
        self.widthBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.widthBox.setPrefix(_fromUtf8(""))
        self.widthBox.setDecimals(5)
        self.widthBox.setSingleStep(0.03125)
        self.widthBox.setObjectName(_fromUtf8("widthBox"))
        self.gridLayout.addWidget(self.widthBox, 4, 1, 1, 1)
        self.genButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.genButton.setObjectName(_fromUtf8("genButton"))
        self.gridLayout.addWidget(self.genButton, 8, 0, 1, 6)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setMargin(0)
        self.label.setIndent(10)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.heightBox = QtGui.QDoubleSpinBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightBox.sizePolicy().hasHeightForWidth())
        self.heightBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.heightBox.setFont(font)
        self.heightBox.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.heightBox.setDecimals(5)
        self.heightBox.setSingleStep(0.03125)
        self.heightBox.setObjectName(_fromUtf8("heightBox"))
        self.gridLayout.addWidget(self.heightBox, 4, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setMargin(0)
        self.label_6.setIndent(10)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setMargin(0)
        self.label_5.setIndent(10)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.jobNameEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.jobNameEdit.setFont(font)
        self.jobNameEdit.setObjectName(_fromUtf8("jobNameEdit"))
        self.gridLayout.addWidget(self.jobNameEdit, 2, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(75, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setMargin(0)
        self.label_2.setIndent(10)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.configButton = QtGui.QToolButton(self.gridLayoutWidget)
        self.configButton.setMinimumSize(QtCore.QSize(0, 22))
        self.configButton.setObjectName(_fromUtf8("configButton"))
        self.gridLayout.addWidget(self.configButton, 8, 6, 1, 1)
        self.doorList = QtGui.QTableWidget(self.gridLayoutWidget)
        self.doorList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.doorList.setObjectName(_fromUtf8("doorList"))
        self.doorList.setColumnCount(7)
        self.doorList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doorList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doorList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doorList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doorList.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doorList.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.doorList.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.doorList.setHorizontalHeaderItem(6, item)
        self.doorList.horizontalHeader().setStretchLastSection(True)
        self.doorList.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.doorList, 7, 0, 1, 7)
        self.importButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.importButton.setFlat(False)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.gridLayout.addWidget(self.importButton, 6, 4, 1, 3)
        self.line = QtGui.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 7)
        self.title = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setScaledContents(False)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName(_fromUtf8("title"))
        self.gridLayout.addWidget(self.title, 0, 0, 1, 7)
        self.itemNumBox = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemNumBox.sizePolicy().hasHeightForWidth())
        self.itemNumBox.setSizePolicy(sizePolicy)
        self.itemNumBox.setMinimumSize(QtCore.QSize(40, 0))
        self.itemNumBox.setMaximumSize(QtCore.QSize(119, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.itemNumBox.setFont(font)
        self.itemNumBox.setObjectName(_fromUtf8("itemNumBox"))
        self.gridLayout.addWidget(self.itemNumBox, 4, 5, 1, 2)
        self.roomNameEdit = QtGui.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Reference Sans Serif"))
        font.setPointSize(10)
        self.roomNameEdit.setFont(font)
        self.roomNameEdit.setObjectName(_fromUtf8("roomNameEdit"))
        self.gridLayout.addWidget(self.roomNameEdit, 2, 4, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.jobNameEdit, self.roomNameEdit)
        Dialog.setTabOrder(self.roomNameEdit, self.widthBox)
        Dialog.setTabOrder(self.widthBox, self.heightBox)
        Dialog.setTabOrder(self.heightBox, self.itemNumBox)
        Dialog.setTabOrder(self.itemNumBox, self.addButton)
        Dialog.setTabOrder(self.addButton, self.importButton)
        Dialog.setTabOrder(self.importButton, self.doorList)
        Dialog.setTabOrder(self.doorList, self.genButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Homestead Sizing App", None))
        self.label_3.setText(_translate("Dialog", "Line #:", None))
        self.addButton.setText(_translate("Dialog", "Add door to list.", None))
        self.widthBox.setSuffix(_translate("Dialog", "\"", None))
        self.genButton.setText(_translate("Dialog", "Generate door sizing programs.", None))
        self.label.setText(_translate("Dialog", "Width:", None))
        self.heightBox.setSuffix(_translate("Dialog", "\"", None))
        self.label_6.setText(_translate("Dialog", "Room: ", None))
        self.label_5.setText(_translate("Dialog", "Job: ", None))
        self.label_2.setText(_translate("Dialog", "Height:", None))
        self.configButton.setToolTip(_translate("Dialog", "Configure Application", None))
        self.configButton.setText(_translate("Dialog", "...", None))
        item = self.doorList.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Page", None))
        item = self.doorList.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Row #", None))
        item = self.doorList.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Width", None))
        item = self.doorList.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Height", None))
        item = self.doorList.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Line #", None))
        item = self.doorList.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Job Name", None))
        item = self.doorList.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Tool #", None))
        self.importButton.setToolTip(_translate("Dialog", "Import a sizing list from an excel file. ", None))
        self.importButton.setText(_translate("Dialog", "Import list from Excel file", None))
        self.title.setText(_translate("Dialog", "Sizing program generator", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

